project/proj1/urls.py
from proj1 import views
from django.views.generic import RedirectView
from django.conf.urls import include,url

app_name='proj1'
urlpatterns=[

              
              url(r'^user_register/',views.user_register,name='user_register'),
              url(r'^user_login/',views.user_login,name='user_login'),
              url(r'^$',views.home1,name='home1'),
              url(r'^proj1/user_login/test/',views.test,name='test'),
              url(r'^questions_list/',views.questions_list,name='questions_list'),
              url(r'^results/',views.results,name='results'),

              
]

project/project/urls.py
from django.conf.urls import include , url
from django.contrib import admin
from proj1 import views
from colleges import views
from branches import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^colleges/', include('colleges.urls')),
    url(r'^proj1/',include('proj1.urls')),
    url(r'^branches/', include('branches.urls')),
]

project/proj1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class USER_LOGIN(models.Model):
    first_name = models.CharField(max_length=35, blank=False)
    last_name = models.CharField(max_length=35, blank=False)
    user_name = models.CharField(max_length=35, blank=False, primary_key=True)
    email_id = models.EmailField(max_length=35, blank=False )
    pass_word = models.CharField(max_length=35, blank=False)
    gender=models.CharField(max_length=10,blank=False)


class Data(models.Model):
    user = models.OneToOneField(USER_LOGIN, on_delete=models.CASCADE)
    quest = models.CharField(max_length=35,blank=False)

# Create your models here.

project/proj1/views.py
from django.shortcuts import render
from proj1.models import USER_LOGIN,User
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.hashers import make_password


def home1(request):
    return render(request,'proj1/home1.html')
def home(request):
    return render(request,'proj1/login.html')
def test(request):
    return render(request,'proj1/test.html')
def questions_list(request):
    return render(request,'proj1/data.html',{})
def index(request):
    messages.info(request, 'successfully Registered!')
    return render(request,'proj1/login.html')
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('uname')
        password = request.POST.get('psw')
        print(username,password)
        user = authenticate(username=username, password=password)
        print(user)
        if user:
            if user.is_active:
                login(request, user)
                return render(request, "proj1/home2.html",{'user':user})
            else:
                return HttpResponse("Account Not Active")

        else:
            print("some tried to login and failed")
           # print("email:{} and password :{}".format(username, password))
            # messages.warning(request, 'Invalid credentials!')
            return render(request, "proj1/login.html")
            # return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'proj1/login.html')
def user_register(request):

     registered=False
     if request.method =='POST':
         if request.POST.get('psw')==request.POST.get('psw-repeat'):

             print("srikar")
             user_name1 = request.POST.get('username')
             pass_word1 = request.POST.get('psw')
             enc_password = make_password(pass_word1)
             user = User(username=user_name1, password=enc_password)
             print(request.POST.get('First_Name'))
             print(request.POST.get('Last_Name'))
             print(user_name1,pass_word1,enc_password)
             print(request.POST.get('Gender'))
             user.email=request.POST.get('email')
             user.save()
             try:

                  user_obj=USER_LOGIN(first_name=request.POST.get('First_Name'),last_name=request.POST.get('Last_Name') ,user_name=request.POST.get('username'),
                            pass_word=request.POST.get('psw'),email_id=request.POST.get('email'),gender=request.POST.get('Gender')
                  )
                  user_obj.save()
                  
                  return render(request,'proj1/login.html')
             except:
                   return HttpResponse("sorry username or email already exist please try with other one!")
   
         else:

              return HttpResponse("both passwords are not matched!")

               
     else:
           return render(request,'proj1/register.html')

def results(request):
    if request.method == 'POST':
        answer = request.POST.get('answer')
        answer1 = request.POST.get('answer1')
        answer2 = request.POST.get('answer2')
        user1=request.user
        ans= answer +'?'+answer1+'?'+answer2
        print(answer,answer1,answer2)
        user_obj1=Data(user=user1,quest=ans)
        user_obj1.save()
        
        return HttpResponse("Hello")



        


# Create your views here.

project/proj1/templates/proj1/data.html
<!doctype html>
<html>
    <title>Analysis Page</title>
    <body>
    
     <form method="POST" action="{% url 'proj1:results' %}">
     <p>1.Which Option do you think best suits u?</p>
     <input type="radio" name="answer" >Working on Building an Automobile like cars,trucks(for MECH)<br>
     <input type="radio" name="answer" > Dealing  with  Digital transmission  of data, circuits ,chips(for  ECE, EEE)<br>
     <input type="radio" name="answer" >Building  websites and technologies related to  comp.programming?(  CSE & IT  )<br>
     <input type="radio" name="answer" >None of the above<br>
     <p>2. Which Subject would you take?</p>
     <input type="radio" name="answer1" >Physics and Mathematics(for MECH)<br>
     <input type="radio" name="answer1" >Basic Electronics(for  ECE, EEE)<br>
     <input type="radio" name="answer1" >Basic Knowledge of Computers,HTML(  CSE & IT  )<br>
     <input type="radio" name="answer1" >None of the above<br>
     <p>3.Not Clear Which side to choose,why not choose both sides?which option would to choose?</p>
     <input type="radio" name="answer2" >Software and Hardware(IT)<br>
     <input type="radio" name="answer2" >Physics and mathematics(MECH)<br>
     <input type="radio" name="answer2" >Electronics(ECE,EEE)<br>
     <input type="radio" name="answer2" >None of the above<br>


     <center> 
            <a class="btn btn-primary" href="results">Submit</a>

     </center>
     
     </form>   
    </body>
    </html>

    


</html>

project/proj1/templates/proj1/home1.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/C8AC6E2B-CAE4-DD4E-9983-14A61648EFB4/main.js" charset="UTF-8"></script><link rel="stylesheet" crossorigin="anonymous" href="https://gc.kis.v2.scr.kaspersky-labs.com/AF8B0C3A-6D5E-EC44-86AD-8E03D54AB562/abn/main.css"/><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Career Guidance</title>
      <style>
      
        #home {
            width: 65px;
            height: 60px;
        }

        
        .container {
  position: relative;
  width: 100%;
  height: 100%;
}

/* Make the image responsive */
.container img {
  width: 100%;
  height: 100%;
}

/* Style the button and place it in the middle of the container/image */
.container .btn {
  position: absolute;
  top: 80%;
  left: 52%;
  transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  background-color: gray;
  color: white;
  font-size: 30px;
  padding: 20px 40px;
  border: none;
  cursor: pointer;
  border-radius: 5px;
}

.container .btn:hover {
  background-color: black;
}
        
h1 {
  text-align: center;
  text-transform: uppercase;
  color: #4CAF50;
}

p {
  text-indent: 40px;
  text-align: center;
  letter-spacing: 2px;
}
        br {
          text-indent: 40px;
  text-align: left; 
            left: 10%;
        }
    
    </style>  
  </head>
  <body>

       <div class="container">
    <img id="img1" style="padding-top: 50px" src="http://www.branchselector.com/wp-content/uploads/2018/06/branch1.jpg" >
        <button type="button"  onclick="location.href='user_login'" style="margin-left : 260px;margin-top: 30px" class="btn btn-info"><b>Get Started with the website</b></button>
    </div>
    
    <div>
        <br>
    
  <h1>How it Works?</h1>
        <p style="font-size:20;">While High School students are always in a dilemma, We make sure they are left with a small amount of clarity in the end about the right Career and Courses 
         to choose from. <br>     Get Started with the Journey and Explore all the way!</p>
    </div>
    </body>
</html>

project/proj1/templates/proj1/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Career Guidance</title>
      <style>
      input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}
          button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}
          button:hover {
  opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}
          .imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
  position: relative;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}
.container {
  padding: 10px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 25px;
  top: 0;
  color: #000;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: red;
  cursor: pointer;
}
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>
  </head>
  <body>
      <form method="post" action="{% url 'proj1:user_login' %}">
          {% csrf_token %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light" >
<a class="navbar-brand" href="#" style="max-width:5%;max-height: 5%">
    <img src="https://www.the-work-guide.com/gallery/decision-making-techniques/decision_making_techniques.jpg" class="img-fluid">
 </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">HOME<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">ABOUT</a>
      </li>
     <li class="nav-item">
        <a class="nav-link" href="#">CONTACT US</a>
        </li>
         <li class="nav-item">
        <a class="nav-link" href="#">FAQ's</a>
        </li>
        </ul>
          </div>
      </nav>
      <h1 style="text-align: center;padding: 5px;font-size: 70px;font-family: serif;color: cadetblue"><strong>ANALYZE MY CAREER!</strong></h1>
      <div class="container">
  <div class="row">
    <div class="col-lg-6">
     <img style="height: 500px;margin-top: 100px;margin-right: 500px" src="https://sg.fiverrcdn.com/photos/104101608/original/51082cbc5434e8622c23abfc1b67b9f9d0ff1569.jpg?1510201166">
    </div>
    <div class="col-lg-6" style="background-color:beige;height: 500px;padding: 50px;margin-top: 100px">
     <form action="action_page.php">
         

        <div class="container">
            <label for="uname"><b>Username</b></label>
            <input type="text" placeholder="Enter Username" name="uname" required>
        
            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" required>
  
    <button type="submit">Submit</button> 
    <button onclick="location.href='user_register'" type="button">
        Register</button>
    


  
        <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
          </label>
        </div>
      
        <div class="container" style="background-color:#f1f1f1">
          <button type="button" class="cancelbtn">Cancel</button>
          <span class="psw">Forgot <a href="#">password?</a></span>
        </div>
      </form>
          </div>
        </div>
      </div>
      
          <!-- Optional JavaScript -->
          <!-- jQuery first, then Popper.js, then Bootstrap JS -->
          <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        </body>
      </html>

project/proj1/templates/proj1/register.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     
    <title>Career Guidance</title>
      <style>
          body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}

      
      
      
      </style>
      
  </head>
  <body>
      
   
      <form method="post" action="{% url 'proj1:user_register' %}">
          {% csrf_token %}
         

  <div class="container">
    <label for="fname"><b>First name</b></label>
    <input type="text" placeholder="Enter Firstname" name="First_Name" required>
     <label for="lname"><b>Last name</b></label>
    <input type="text" placeholder="Enter Lastname" name="Last_Name" required>
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>
    
    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" required>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
    <label for="psw-repeat"><b> Confirm-Password</b></label>
    <input type="password" placeholder="Confirm Password" name="psw-repeat" required>
      <label for="Gender"><b>Gender</b>
     <input type="radio" name="Gender" value="male"> Male
     <input type="radio" name="Gender" value="female"> Female<br>
      </label>

    
  

  <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

    <button type="submit" class="registerbtn">Register</button>
         </div>
         
  
  <div class="container signin">
    <p>Already have an account? <a href="#">Sign in</a>.</p>
  </div>
</form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

project/proj1/templates/proj1/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>

<h2>Successfully questions are attempted</h2>
</body>
</html>

project/proj1/templates/proj1/test.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'proj1/sc2.css' %}">

    <title>Career Guidance</title>
      
  </head>
  <body>
      <form method="get" action="{% url 'proj1:test' %}">
          {% csrf_token %}
      
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="#" style="max-width:5%;max-height: 5%">
    <img src="https://www.the-work-guide.com/gallery/decision-making-techniques/decision_making_techniques.jpg" class="img-fluid">
 </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">HOME<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">ABOUT</a>
      </li>
     <li class="nav-item">
        <a class="nav-link" href="#">CONTACT US</a>
        </li>
         <li class="nav-item">
        <a class="nav-link" href="#">FAQ's</a>
        </li>
        
     
    </ul>
  
            
      <input class="search" type="search" placeholder="Enter College Name" aria-label="Search" >
      <button class="btn btn-outline-success" type="submit">SEARCH</button>
   <a class="navbar-brand" href="#" style="max-width:4% ; max-height: 4%">
   <img src="https://t4.ftcdn.net/jpg/01/16/06/45/240_F_116064582_KlXENacGmdt4xl8H6fQRYfSZLntLNKSX.jpg" class="img-fluid">
 </a>
     
  </div>
</nav>
    
       
       <div class="container1">
   
    <div class="row">
        <div class="col-md-12">
            <img style='float:left;width:200px;height:200px; margin-right:10px;' src="https://cognigen-cellular.com/images/b-clipart-later-6.gif" />
            <h1 style="margin-top: 60px">Career Guidance to Success</h1>
            <p style="margin-right : 1000px">Find the stream you suit for!</p>
        </div>
    </div>
      </div>
      <div class="w3container">
   <h2 style="margin-left: 100px;padding-top: 15px;text-align: center">CAREER TEST TO PLAN YOUR FUTURE</h2><br>
          <h5 style="margin-left: 100px;padding-top: 25px">How it works?</h5>
          <p style="margin-left: 100px;padding-top: 25px">This is a internet based career test.This test asks multiple questions to understand your interests and personality to make recommondations on streams you may be suited for.</p>
          
          <a class="btn btn-primary" href="questions_list">Start Test</a>
              
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>